### PR TITLE
Actual fix for #7 prevent https from being redirected to http.

### PR DESCRIPTION
**Pull request by raistlinthewiz**

### CODE REVIEW

**Comment by raistlinthewiz** [comment]
https://github.com/thenativeweb/forcedomain/pull/10#issuecomment-219746421 - @goloroden hopefully you can merge this :)

**Comment by raistlinthewiz** [comment]
@goloroden were you able to check this?

**Comment by goloroden** [comment]
Thanks for the PR, I have just merged it and will publish a new version of the package to npm in a few minutes :-)

One final thing: If you want to, could you please send another PR that contains your name and email address in the `package.json` file as a contributor?

**Comment by raistlinthewiz** [comment]
sure let me do so.

**Comment by raistlinthewiz** [comment]
https://github.com/thenativeweb/forcedomain/pull/15

**Pull request merged**
