### PR TITLE
exclude regex rule, 127.0.0.1

### PR DESCRIPTION
**Pull request by yegortokmakov**
hi

I've added support for hostname exclusion by a regular expression. 
Might be useful for heroku review apps or any other environment.

Additionally, added `127.0.0.1` to excluded IPs.

Cheers

### CODE REVIEW

**Comment by yegortokmakov** [comment]
Hi @goloroden , could you have a look?

**Comment by goloroden** [comment]
Hi @yegortokmakov 😊 

I'm really sorry for not having responded yet. Hence it's good that you pinged me!

I will take a look at your PR within the next 24 hours, and then get back to you with feedback!

**Comment by goloroden** [comment]
PS: One thing … would you mind adding yourself to the list of contributors in the `package.json` file?

**Comment by goloroden** [comment]
LGTM, I would like to merge it, as soon as you have added yourself to the `package.json` file (or as soon as you told me that you do not want this).

**Comment by yegortokmakov** [comment]
@goloroden done

thanks for the lib!

**Comment by goloroden** [comment]
Just published a new version, `0.8.1`, that contains your changes.

Thanks for it :-)

**Pull request merged**
