### PR TITLE
Fix 301 default

### PR DESCRIPTION
**Pull request by KeitIG**
#11

### CODE REVIEW

**Comment by goloroden** [comment]
LGTM :-)
Thanks a lot for your work :-)

Just one more question before I am going to merge it: Would you mind adding yourself to the `package.json` file?

**Comment by KeitIG** [comment]
Thanks for the opportunity :) I'm also having a look at the build error, I must have missed something

**Comment by goloroden** [comment]
Great, thanks :-)

Regarding the build server … I'm not too sure about whether it's actually your fault, maybe the CI is currently mis-configured. I need to check this as well :-)

**Comment by goloroden** [comment]
PS: I found the issue, there were actually some tests not yet updated. I have fixed it, CI build is green :-)

Will release a new version now.

Again, thanks a lot for your effort :-)))

**Pull request merged**
