### PR TITLE
Fix #7 prevent https from being redirected to http

### LINKED ISSUE #7: prevent https from being redirected to http
So I'm using it as following and my site uses the following;

```javascript
app.use(forceDomain({ hostname: 'www.mydomain.com' }));
```

The thing is that it tries to redirect to http version of the same url within https - this should be prevented.

### PR DESCRIPTION
**Pull request by riversy**
It should fix the problem with permanent 'protocol'. We just get it from functiion parameters if it wasn't defined in options instead of use 'http' by default.

### CODE REVIEW

**Comment by goloroden** [comment]
Sorry for not having answered to this PR for such a long time.

I have seen that the tests fail, and that the `master` branch has moved forward meanwhile.

Would you mind adjusting things so that the tests work, and that your PR can be merged?

**Comment by riversy** [comment]
Oh, I was in a hurry and didn't update tests. I will adjust things and resubmit PR then.
Thank you for have had a look.

**Comment by goloroden** [comment]
Great, thanks :-)

And thanks, too, for not being mad at me that it took so long to reply.

**Comment by raistlinthewiz** [comment]
will merge this?

**Comment by goloroden** [comment]
@raistlinthewiz As soon as [these things](https://github.com/thenativeweb/forcedomain/pull/10#issuecomment-176038066) are fixed, I'd love to :-)

**Comment by goloroden** [comment]
Superseeded by 418b9fabbd118a9d49c6e3b426ae6ae9dbafdf7e, hence closed

**Pull request closed without merging**
